const RELOAD_ALL_CONTEXTMENU_ITEM_ID = "RELOAD_ALL";
const RELOAD_ALL_CONTEXTMENU_ITEM_TITLE = "Reload All";

const RELOAD_OTHER_CONTEXTMENU_ITEM_ID = "RELOAD_OTHER";
const RELOAD_OTHER_CONTEXTMENU_ITEM_TITLE = "Reload Other";

const CLOSE_OTHER_CONTEXTMENU_ITEM_ID = "CLOSE_OTHER";
const CLOSE_OTHER_CONTEXTMENU_ITEM_TITLE = "Close other";

const CLOSE_ALL_CONTEXTMENU_ITEM_ID = "CLOSE_ALL";
const CLOSE_ALL_CONTEXTMENU_ITEM_TITLE = "Close All";

const MUTE_ALL_CONTEXTMENU_ITEM_ID = "MUTE_ALL";
const MUTE_ALL_CONTEXTMENU_ITEM_TITLE = "Mute All";

const MUTE_OTHER_CONTEXTMENU_ITEM_ID = "MUTE_OTHER";
const MUTE_OTHER_CONTEXTMENU_ITEM_TITLE = "Mute other";

const UNMUTE_ALL_CONTEXTMENU_ITEM_ID = "UNMUTE_ALL";
const UNMUTE_ALL_CONTEXTMENU_ITEM_TITLE = "Unmute All";

const UNMUTE_OTHER_CONTEXTMENU_ITEM_ID = "UNMUTE_OTHER";
const UNMUTE_OTHER_CONTEXTMENU_ITEM_TITLE = "Unmute other";